###Autenticat sys user
POST {{host}}/auth/signin
Content-Type: application/json

{
    "username":"root",
    "password":"Aqwerty123*"
}
#### Autenticar usuario
POST {{host}}/auth/signin
Content-Type: application/json

{
    "username":"john",
    "password":"Aqwerty123*"
}
#### Autenticar usuario agente
POST {{host}}/auth/signin/agent
Content-Type: application/json

{
    "username":"john",
    "password":"Aqwerty123*"
}
#### Autenticar tecnico
POST {{host}}/auth/signin/tech
Content-Type: application/json

{
    "username":"pepe",
    "password":"Aqwerty123*"
}
### Datos de un usuario
{{host}}/users/user/john
Authorization: Bearer {{auth}}

### Listado de usuarios
{{host}}/users?page=1
Authorization: Bearer {{auth}}

#### Crear usuario
POST {{host}}/users/user
Authorization: Bearer {{auth}}
Content-Type: application/json

{
    "username":"john3",
    "password":"Aqwerty123*",
    "name":"Juan Pablo",
    "lastname":"Bacallao Castillo"
}
#### Registrar usuario
POST {{host}}/users/register
Content-Type: application/json

{
    "username":"johnp",
    "password":"Aqwerty123*",
    "name":"Juan Pablo",
    "lastname":"Bacallao Castillo",
    "email":"john891226@gmail.com"
}
#### Enviar correo de verificacion
POST {{host}}/auth/confirmation
Content-Type: application/json

{
    "username":"johnp",
    "email":"john891226@gmail.com"
}
#### Confirmar codigo de verificacion
POST {{host}}/auth/confirmation/johnp
Content-Type: application/json

{
    "code":"653261"
}
#### Actualizar usuario
PUT {{host}}/users/user/john
Authorization: Bearer {{auth}}
Content-Type: application/json

{
    "last_password":"Aqwerty123*",
    "new_password":"Aqwerty123*",
    "confirm_password":"Aqwerty123*",
    "expiration_date":null
}
#### Crear agente
POST {{host}}/users/agent
Authorization: Bearer {{auth}}
Content-Type: application/json

{
    "role":1,
    "new_user":{
        "username":"wendy",
        "password":"Aqwerty123*",
        "name":"Wendy",
        "lastname":"Torres"
    },
    "expiration_date":"2020-1-1"
}
PUT {{host}}/users/agent/wendy
#### Actualizar agente
Authorization: Bearer {{auth}}
Content-Type: application/json

{
    "active":true
}
#### Crear tecnico
POST {{host}}/users/tech
Authorization: Bearer {{auth}}
Content-Type: application/json

{
    "username":"john2222",
    "address":"asdasd",
    "confirmed":true,
    "ci":"89122620343",
    "province":15,
    "confirmation_photo": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABQAA",
    "municipality":32,
    "habilities":[34]
}
### Actualizar tecnico
PUT {{host}}/users/tech/pepe
Authorization: Bearer {{auth}}
Content-Type: application/json

{
    "active":true,
    "expiration_date":null
}
### Retorna funcionalidades
{{host}}/functionalities
Authorization: Bearer {{auth}}
### Retorna los roles
{{host}}/roles
Authorization: Bearer {{auth}}
### Devuelve las provincias
{{host}}/enums/provinces
Authorization: Bearer {{auth}}
### Devuelve los municipios de una provincia
{{host}}/enums/municipalities/15
Authorization: Bearer {{auth}}
### Crea un rol
POST {{host}}/roles
Authorization: Bearer {{auth}}
Content-Type: application/json

{
    "name":"test2",
    "functionalities":[
        "manage_users",
        "manage_roles"
    ]
}
### Adiciona funcionalidades a un rol
POST {{host}}/roles/3/manage_users,manage_capabilities
Authorization: Bearer {{auth}}
Content-Type: application/json
### Elimina funcionalidades a un rol
DELETE {{host}}/roles/3/manage_users,manage_capabilities
Authorization: Bearer {{auth}}
Content-Type: application/json
### Crea un grupo
POST {{host}}/enums/habilities
Authorization: Bearer {{auth}}
Content-Type: application/json

{
    "name":"Grupo12"
}

### Devuelve listado de grupos y habilidades
{{host}}/enums/habilities
Authorization: Bearer {{auth}}

### Crea habilidades en un grupo
POST {{host}}/enums/habilities/1
Authorization: Bearer {{auth}}
Content-Type: application/json

{
    "name":"Habilidad 11",
    "requirements":[
        {
            "name":"ayudante"
        }
    ]
}

### Crea nuevos grupos
POST {{host}}/enums/issues
Authorization: Bearer {{auth}}
Content-Type: multipart/form-data; charset=utf-8; boundary="boundary"

--boundary
Content-Disposition: form-data; name="name"

title
--boundary
Content-Disposition: form-data; name="questions"

[
    {
        "name":4
    }
]
--boundary--
### User funcs
{{host}}/auth/user_info
Authorization: Bearer {{auth}}