POST http://localhost:4000/auth/signin
Content-Type: application/json

{
    "username":"root",
    "password":"Aqwerty123*"
}
####
POST http://localhost:4000/auth/signin
Content-Type: application/json

{
    "username":"john",
    "password":"Aqwerty123*"
}
####
POST http://localhost:4000/auth/signin/agent
Content-Type: application/json

{
    "username":"wendy",
    "password":"Aqwerty123*"
}
####
POST http://localhost:4000/auth/signin/tech
Content-Type: application/json

{
    "username":"pepe",
    "password":"Aqwerty123*"
}
####
POST http://localhost:4000/users/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJhZ2VudCI6eyJ1c2VyIjoxLCJleHBpcmF0aW9uX2RhdGUiOm51bGwsImFjdGl2ZSI6dHJ1ZX0sInRlY2giOm51bGwsImlzUm9vdCI6ZmFsc2UsImlhdCI6MTYxNzg1Mjc3OSwiZXhwIjoxNjE3ODY3MTc5fQ.AjsFsIZ0TrFIHPP2v3mzbusBfV_sKsweojxoG8fJSF8
Content-Type: application/json

{
    "username":"john",
    "password":"Aqwerty123*",
    "name":"Juan Pablo",
    "lastname":"Bacallao Castillo"
}
####
PUT http://localhost:4000/users/user/john
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJhZ2VudCI6eyJ1c2VyIjoxLCJleHBpcmF0aW9uX2RhdGUiOm51bGwsImFjdGl2ZSI6dHJ1ZX0sInRlY2giOm51bGwsImlzUm9vdCI6ZmFsc2UsImlhdCI6MTYxNzg1Mjc3OSwiZXhwIjoxNjE3ODY3MTc5fQ.AjsFsIZ0TrFIHPP2v3mzbusBfV_sKsweojxoG8fJSF8
Content-Type: application/json

{
    "last_password":"Aqwerty123*",
    "new_password":"Aqwerty123*",
    "confirm_password":"Aqwerty123*",
    "expiration_date":null
}
####
POST http://localhost:4000/users/agent
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJhZ2VudCI6eyJ1c2VyIjoxLCJleHBpcmF0aW9uX2RhdGUiOm51bGwsImFjdGl2ZSI6dHJ1ZX0sInRlY2giOm51bGwsImlzUm9vdCI6ZmFsc2UsImlhdCI6MTYxNzg1Mjc3OSwiZXhwIjoxNjE3ODY3MTc5fQ.AjsFsIZ0TrFIHPP2v3mzbusBfV_sKsweojxoG8fJSF8
Content-Type: application/json

{
    "role":1,
    "new_user":{
        "username":"wendy",
        "password":"Aqwerty123*",
        "name":"Wendy",
        "lastname":"Torres"
    },
    "expiration_date":"2020-1-1"
}
####
PUT http://localhost:4000/users/agent/wendy
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJhZ2VudCI6eyJ1c2VyIjoxLCJleHBpcmF0aW9uX2RhdGUiOm51bGwsImFjdGl2ZSI6dHJ1ZX0sInRlY2giOm51bGwsImlzUm9vdCI6ZmFsc2UsImlhdCI6MTYxNzg1Mjc3OSwiZXhwIjoxNjE3ODY3MTc5fQ.AjsFsIZ0TrFIHPP2v3mzbusBfV_sKsweojxoG8fJSF8
Content-Type: application/json

{
    "active":true
}
####
POST http://localhost:4000/users/tech
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJhZ2VudCI6eyJ1c2VyIjoxLCJleHBpcmF0aW9uX2RhdGUiOm51bGwsImFjdGl2ZSI6dHJ1ZX0sInRlY2giOm51bGwsImlzUm9vdCI6ZmFsc2UsImlhdCI6MTYxNzg1Mjc3OSwiZXhwIjoxNjE3ODY3MTc5fQ.AjsFsIZ0TrFIHPP2v3mzbusBfV_sKsweojxoG8fJSF8
Content-Type: application/json

{
    "new_user":{
        "username":"pepe",
        "password":"Aqwerty123*",
        "name":"PEpito",
        "lastname":"El cojo"
    }
}
###
PUT http://localhost:4000/users/tech/pepe
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJhZ2VudCI6eyJ1c2VyIjoxLCJleHBpcmF0aW9uX2RhdGUiOm51bGwsImFjdGl2ZSI6dHJ1ZX0sInRlY2giOm51bGwsImlzUm9vdCI6ZmFsc2UsImlhdCI6MTYxNzg1Mjc3OSwiZXhwIjoxNjE3ODY3MTc5fQ.AjsFsIZ0TrFIHPP2v3mzbusBfV_sKsweojxoG8fJSF8
Content-Type: application/json

{
    "active":true,
    "expiration_date":null
}
###
http://localhost:4000/functionalities
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJhZ2VudCI6eyJ1c2VyIjoxLCJleHBpcmF0aW9uX2RhdGUiOm51bGwsImFjdGl2ZSI6dHJ1ZX0sInRlY2giOm51bGwsImlzUm9vdCI6ZmFsc2UsImlhdCI6MTYxNzg1Mjc3OSwiZXhwIjoxNjE3ODY3MTc5fQ.AjsFsIZ0TrFIHPP2v3mzbusBfV_sKsweojxoG8fJSF8
###
http://localhost:4000/roles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJhZ2VudCI6eyJ1c2VyIjoxLCJleHBpcmF0aW9uX2RhdGUiOm51bGwsImFjdGl2ZSI6dHJ1ZX0sInRlY2giOm51bGwsImlzUm9vdCI6ZmFsc2UsImlhdCI6MTYxNzg1Mjc3OSwiZXhwIjoxNjE3ODY3MTc5fQ.AjsFsIZ0TrFIHPP2v3mzbusBfV_sKsweojxoG8fJSF8
###
http://localhost:4000/enums/provinces
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJhZ2VudCI6eyJ1c2VyIjoxLCJleHBpcmF0aW9uX2RhdGUiOm51bGwsImFjdGl2ZSI6dHJ1ZX0sInRlY2giOm51bGwsImlzUm9vdCI6ZmFsc2UsImlhdCI6MTYxNzg1Mjc3OSwiZXhwIjoxNjE3ODY3MTc5fQ.AjsFsIZ0TrFIHPP2v3mzbusBfV_sKsweojxoG8fJSF8
###
http://localhost:4000/enums/municipalities/15
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJhZ2VudCI6eyJ1c2VyIjoxLCJleHBpcmF0aW9uX2RhdGUiOm51bGwsImFjdGl2ZSI6dHJ1ZX0sInRlY2giOm51bGwsImlzUm9vdCI6ZmFsc2UsImlhdCI6MTYxNzg1Mjc3OSwiZXhwIjoxNjE3ODY3MTc5fQ.AjsFsIZ0TrFIHPP2v3mzbusBfV_sKsweojxoG8fJSF8
###
POST http://localhost:4000/roles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJhZ2VudCI6eyJ1c2VyIjoxLCJleHBpcmF0aW9uX2RhdGUiOm51bGwsImFjdGl2ZSI6dHJ1ZX0sInRlY2giOm51bGwsImlzUm9vdCI6ZmFsc2UsImlhdCI6MTYxNzg1Mjc3OSwiZXhwIjoxNjE3ODY3MTc5fQ.AjsFsIZ0TrFIHPP2v3mzbusBfV_sKsweojxoG8fJSF8
Content-Type: application/json

{
    "name":"test2",
    "functionalities":[
        "manage_users",
        "manage_roles"
    ]
}
###
POST http://localhost:4000/roles/3/manage_users,manage_capabilities
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJhZ2VudCI6eyJ1c2VyIjoxLCJleHBpcmF0aW9uX2RhdGUiOm51bGwsImFjdGl2ZSI6dHJ1ZX0sInRlY2giOm51bGwsImlzUm9vdCI6ZmFsc2UsImlhdCI6MTYxNzg1Mjc3OSwiZXhwIjoxNjE3ODY3MTc5fQ.AjsFsIZ0TrFIHPP2v3mzbusBfV_sKsweojxoG8fJSF8
Content-Type: application/json
###
DELETE http://localhost:4000/roles/3/manage_users,manage_capabilities
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJhZ2VudCI6eyJ1c2VyIjoxLCJleHBpcmF0aW9uX2RhdGUiOm51bGwsImFjdGl2ZSI6dHJ1ZX0sInRlY2giOm51bGwsImlzUm9vdCI6ZmFsc2UsImlhdCI6MTYxNzg1Mjc3OSwiZXhwIjoxNjE3ODY3MTc5fQ.AjsFsIZ0TrFIHPP2v3mzbusBfV_sKsweojxoG8fJSF8
Content-Type: application/json
###
POST http://localhost:4000/enums/habilities
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJhZ2VudCI6eyJ1c2VyIjoxLCJleHBpcmF0aW9uX2RhdGUiOm51bGwsImFjdGl2ZSI6dHJ1ZX0sInRlY2giOm51bGwsImlzUm9vdCI6ZmFsc2UsImlhdCI6MTYxNzg1Mjc3OSwiZXhwIjoxNjE3ODY3MTc5fQ.AjsFsIZ0TrFIHPP2v3mzbusBfV_sKsweojxoG8fJSF8
Content-Type: application/json

{
    "name":"Grupo12"
}

###
POST http://localhost:4000/enums/habilities/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJhZ2VudCI6eyJ1c2VyIjoxLCJleHBpcmF0aW9uX2RhdGUiOm51bGwsImFjdGl2ZSI6dHJ1ZX0sInRlY2giOm51bGwsImlzUm9vdCI6ZmFsc2UsImlhdCI6MTYxNzg1Mjc3OSwiZXhwIjoxNjE3ODY3MTc5fQ.AjsFsIZ0TrFIHPP2v3mzbusBfV_sKsweojxoG8fJSF8
Content-Type: application/json

{
    "name":"Habilidad 11",
    "requirements":[
        {
            "name":"ayudante"
        }
    ]
}