export const TECH_APPLICANT = 'tech_applicant';
export const TECH_APPLICANT_CONFIRMED = 'TECH_APPLICANT_CONFIRMED';
export const TECH_APPLICANT_CANCELLED = 'TECH_APPLICANT_CANCELLED';
export const ISSUE_CREATED='ISSUE_CREATED'
