export const TECH_APPLICANT = 'tech_applicant';
export const TECH_APPLICANT_CONFIRMED = 'TECH_APPLICANT_CONFIRMED';
export const TECH_APPLICANT_CANCELLED = 'TECH_APPLICANT_CANCELLED';
export const ISSUE_CREATED = 'ISSUE_CREATED';
export const ISSUE_UNAVAILABLE = 'ISSUE_UNAVAILABLE';
export const NEW_ISSUE_APPLICATION = 'NEW_ISSUE_APPLICATION';
export const ISSUE_APPLICATION_CANCELLED = 'ISSUE_APPLICATION_CANCELLED';
export const ISSUE_IGNORED = 'ISSUE_IGNORED';
export const ISSUE_CANCELLED = 'ISSUE_CANCELLED';
export const TECH_ACCEPTED = 'TECH_ACCEPTED';
export const TECH_REJECTED = 'TECH_REJECTED';
export const NEW_TECHAPPLICATION = 'NEW_TECHAPPLICATION';
export const NEW_TECHAPPLICATION_CONFIRMATION =
  'NEW_TECHAPPLICATION_CONFIRMATION';
export const ISSUE_IN_PROGRESS = 'ISSUE_IN_PROGRESS';
export const TECH_ARRIVED = 'TECH_ARRIVED';
export const ISSUE_ON_THE_WAY = 'ISSUE_ON_THE_WAY';
export const CLIENT_ISSUE_IN_PROGRESS_UPDATE =
  'CLIENT_ISSUE_IN_PROGRESS_UPDATE';
export const TECH_ISSUE_IN_PROGRESS_UPDATE = 'TECH_ISSUE_IN_PROGRESS_UPDATE';
export const ISSUE_STARTED = 'ISSUE_STARTED';
export const ISSUE_PAUSED = 'ISSUE_PAUSED';
export const ISSUE_RESUMED = 'ISSUE_RESUMED';
export const ISSUE_FINISHED = 'ISSUE_FINISHED';
export const TECH_ISSUE_FINISHED = 'TECH_ISSUE_FINISHED';
export const PENDENT_RATING = 'PENDENT_RATING';
