export const TECH_APPLICANT = 'tech_applicant';
export const TECH_APPLICANT_CONFIRMED = 'TECH_APPLICANT_CONFIRMED';
export const TECH_APPLICANT_CANCELLED = 'TECH_APPLICANT_CANCELLED';
export const ISSUE_CREATED = 'ISSUE_CREATED';
export const ISSUE_UNAVAILABLE = 'ISSUE_UNAVAILABLE';
export const NEW_ISSUE_APPLICATION = 'NEW_ISSUE_APPLICATION';
export const ISSUE_IGNORED = 'ISSUE_IGNORED';
export const ISSUE_CANCELLED = 'ISSUE_CANCELLED';
