
### Crea un grupo
POST {{host}}/enums/habilities
Authorization: Bearer {{auth}}
Content-Type: application/json

{
    "name":"Grupo12"
}

### Devuelve listado de grupos y habilidades
{{host}}/enums/habilities
Authorization: Bearer {{auth}}

### Crea habilidades en un grupo
POST {{host}}/enums/habilities/1
Authorization: Bearer {{auth}}
Content-Type: application/json

{
    "name":"Habilidad 11",
    "requirements":[
        {
            "name":"ayudante"
        }
    ]
}

### Crea nuevos grupos
POST {{host}}/enums/issues
Authorization: Bearer {{auth}}
Content-Type: multipart/form-data; charset=utf-8; boundary="boundary"

--boundary
Content-Disposition: form-data; name="name"

title
--boundary
Content-Disposition: form-data; name="questions"

[
    {
        "name":4
    }
]
--boundary--

### Get all coins
{{host}}/enums/coins
Authorization: Bearer {{auth}}

### crear moneda
POST {{host}}/enums/coins
Authorization: Bearer {{auth}}
Content-Type: application/json

{
  "name": "CUP",
  "factor": 1,
  "active": true
}

### Borrar moneda
DELETE  {{host}}/enums/coins/1
Authorization: Bearer {{auth}}

### Get active licenses
{{host}}/enums/licenses
Authorization: Bearer {{auth}}